import './Terms.css';

const SECTIONS = [
  {
    number: '1',
    title: 'Definitions and Interpretation',
    content: [
      { sub: '1.1', text: '"Platform" means the ARIA Financial Intelligence Software, including all modules, sub-systems, APIs, dashboards, databases, automation workflows, machine learning components, forecasting engines, fraud detection systems, reconciliation protocols, and any ancillary software, tools, or services provided by Helix XI Technologies.' },
      { sub: '1.2', text: '"Financial Data" means any numerical, transactional, ledger, invoicing, forecasting, payroll, tax, or other financially sensitive information processed, stored, transmitted, or analyzed by the Platform.' },
      { sub: '1.3', text: '"Output" means any report, forecast, ledger entry, anomaly alert, fraud score, reconciliation result, dashboard visualization, or other artifact generated by the Platform, whether produced autonomously or in response to User input.' },
      { sub: '1.4', text: '"Aggregate Data" means anonymized, de-identified, and statistically processed data derived from User interactions with the Platform, from which no individual, entity, or transaction can be identified, directly or indirectly.' },
      { sub: '1.5', text: '"Subscription" means any paid tier of access to the Platform, including but not limited to Starter, Professional, and Enterprise plans, as defined in the current pricing schedule published by Helix XI Technologies.' },
    ]
  },
  {
    number: '2',
    title: 'License Grant and Restrictions',
    content: [
      { sub: '2.1', label: 'Limited License.', text: 'Subject to full compliance with these Terms and timely payment of all applicable Subscription fees, Helix XI Technologies hereby grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Platform solely for your internal business purposes.' },
      { sub: '2.2', label: 'Restrictions.', text: 'You shall not: (a) copy, modify, adapt, translate, or create derivative works based on the Platform; (b) reverse engineer, disassemble, decompile, or otherwise attempt to derive source code; (c) sell, resell, rent, lease, sublicense, or otherwise transfer rights to the Platform; (d) use the Platform to build a competitive product or service; (e) remove or alter any proprietary notices or labels on the Platform; (f) use the Platform in any manner that could damage, disable, overburden, or impair the Platform or servers.' },
      { sub: '2.3', label: 'Reservation of Rights.', text: 'Helix XI Technologies reserves all rights not expressly granted herein. No implied licenses are granted under this Agreement. All rights in the Platform, including all intellectual property rights therein, remain exclusively with Helix XI Technologies.' },
    ]
  },
  {
    number: '3',
    title: 'Disclaimer of Warranties and Limitation of Liability',
    warning: 'THE PLATFORM IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HELIX XI TECHNOLOGIES EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO: (a) Any implied warranty of merchantability, fitness for a particular purpose, title, or non-infringement; (b) That the Platform will meet your specific requirements or expectations; (c) That the Platform will be uninterrupted, error-free, secure, or free from viruses, malware, or other harmful components; (d) That any Output generated by the Platform is accurate, complete, reliable, current, or suitable for any particular financial, legal, regulatory, or accounting purpose; (e) That the Platform complies with any specific accounting standards, tax regulations, or jurisdiction-specific legal obligations.',
    content: [
      { sub: '3.2', text: 'THE PLATFORM IS AN AUTOMATION AND INTELLIGENCE AID. ALL OUTPUT PRODUCED BY THE PLATFORM MUST BE INDEPENDENTLY VERIFIED BY QUALIFIED FINANCIAL PROFESSIONALS BEFORE BEING RELIED UPON FOR ANY FINANCIAL DECISION, TAX FILING, AUDIT, REGULATORY SUBMISSION, OR LEGAL PURPOSE. THE PLATFORM DOES NOT CONSTITUTE FINANCIAL ADVICE, ACCOUNTING ADVICE, TAX ADVICE, OR LEGAL ADVICE OF ANY KIND.' },
      { sub: '3.3', label: 'Limitation of Liability.', text: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL HELIX XI TECHNOLOGIES, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, LICENSORS, OR REPRESENTATIVES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO: LOSS OF PROFITS, LOSS OF REVENUE, LOSS OF DATA, FINANCIAL LOSSES, BUSINESS INTERRUPTION, REGULATORY PENALTIES, TAX LIABILITIES, AUDIT FINDINGS, OR ANY OTHER INTANGIBLE LOSSES.' },
      { sub: '3.4', label: 'Maximum Aggregate Liability.', text: "HELIX XI TECHNOLOGIES' TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY AND ALL CLAIMS SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL FEES PAID BY YOU IN THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED UNITED STATES DOLLARS (USD $100.00)." },
    ]
  },
  {
    number: '4',
    title: 'User Responsibilities and Indemnification',
    content: [
      { sub: '4.1', label: 'User Responsibilities.', text: 'You are solely responsible for: (a) the accuracy and completeness of all data you input into the Platform; (b) independently verifying all Output before acting upon it; (c) ensuring the Platform is appropriate for your intended use case; (d) maintaining adequate backup copies of all Financial Data; (e) compliance with all applicable financial, tax, and regulatory requirements in your jurisdiction.' },
      { sub: '4.2', label: 'Indemnification.', text: 'You agree to indemnify, defend, and hold harmless Helix XI Technologies and its affiliates, officers, directors, employees, agents, and representatives from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys\' fees) arising out of or relating to your use or misuse of the Platform, your reliance on any Output without independent professional verification, or your violation of these Terms.' },
      { sub: '4.3', label: 'Professional Verification Obligation.', text: 'You expressly acknowledge and agree that the Platform is not a substitute for qualified professional financial, accounting, tax, or legal advice. You assume full responsibility for engaging appropriately qualified professionals to review, verify, and validate all Platform Output before such Output is acted upon or relied upon.' },
    ]
  },
  {
    number: '5',
    title: 'Data, Privacy, and Aggregate Usage Rights',
    content: [
      { sub: '5.1', label: 'Data Ownership.', text: 'As between you and Helix XI Technologies, you retain ownership of all Financial Data you submit to the Platform. You grant Helix XI Technologies a limited, worldwide, royalty-free license to process, store, and transmit your Financial Data solely to the extent necessary to provide the Platform services to you.' },
      { sub: '5.2', label: 'Aggregate Data Rights.', text: 'You hereby grant Helix XI Technologies a perpetual, irrevocable, worldwide, royalty-free license to collect, process, analyze, and use Aggregate Data derived from your use of the Platform for improving the Platform, developing new features, generating industry benchmarks, training machine learning models, and publishing anonymized statistical analyses.' },
      { sub: '5.3', label: 'Platform Intelligence.', text: 'All improvements to the Platform\'s artificial intelligence, machine learning models, fraud scoring algorithms, and forecasting models that result from processing Aggregate Data shall be the exclusive intellectual property of Helix XI Technologies.' },
      { sub: '5.4', label: 'Security.', text: 'Helix XI Technologies implements commercially reasonable technical and organizational measures to protect Financial Data. However, no method of transmission over the internet is completely secure. Helix XI Technologies cannot guarantee absolute security.' },
    ]
  },
  {
    number: '6',
    title: 'Subscription, Billing, and Payment Terms',
    content: [
      { sub: '6.1', label: 'Subscription Tiers.', text: 'Access to the Platform is provided on a subscription basis. Current subscription tiers, pricing, and feature allocations are as set out in the Helix XI Technologies pricing schedule, which may be updated from time to time with thirty (30) days\' notice.' },
      { sub: '6.2', label: 'Auto-Renewal.', text: 'All Subscriptions automatically renew at the end of each billing period unless you provide written notice of cancellation at least thirty (30) days prior to the end of the then-current billing period.' },
      { sub: '6.3', label: 'No Refunds.', text: 'All fees paid to Helix XI Technologies are non-refundable except as expressly required by applicable law. No refunds or credits will be provided for partial periods of service, unused features, or unused Subscription capacity.' },
      { sub: '6.4', label: 'Usage-Based Features.', text: 'Certain features of the Platform may be subject to usage-based pricing. Usage metrics and billing calculations shall be determined by Helix XI Technologies\' systems, and such determinations shall be final and binding absent manifest error.' },
    ]
  },
  {
    number: '7',
    title: 'Intellectual Property',
    content: [
      { sub: '7.1', label: 'Ownership.', text: 'The Platform, including all software, algorithms, machine learning models, user interfaces, documentation, trademarks, trade names, logos, and all other intellectual property embodied therein, is and shall remain the exclusive property of Helix XI Technologies.' },
      { sub: '7.2', label: 'Feedback.', text: 'If you provide Helix XI Technologies with any feedback, suggestions, or ideas regarding the Platform, you hereby assign to Helix XI Technologies all right, title, and interest in and to such Feedback. Helix XI Technologies may use such Feedback for any purpose without restriction, attribution, or compensation to you.' },
    ]
  },
  {
    number: '8',
    title: 'Termination',
    content: [
      { sub: '8.1', label: 'Termination by Helix XI.', text: 'Helix XI Technologies reserves the right to suspend or terminate your access to the Platform at any time, with or without cause, with or without notice, effective immediately. Grounds for termination include breach of these Terms, non-payment of fees, fraudulent activity, or actions determined to be harmful to the Platform or its users.' },
      { sub: '8.2', label: 'Effect of Termination.', text: 'Upon termination for any reason: (a) all licenses granted herein immediately cease; (b) you must immediately cease all use of the Platform; (c) Sections 3, 4, 5.2, 5.3, 7, 9, 10, and 11 shall survive termination indefinitely.' },
    ]
  },
  {
    number: '9',
    title: 'Governing Law and Dispute Resolution',
    content: [
      { sub: '9.1', label: 'Governing Law.', text: 'These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising under or in connection with these Terms shall be resolved exclusively through binding arbitration, and the decision of the arbitrator shall be final and binding upon both parties.' },
      { sub: '9.2', label: 'Class Action Waiver.', text: 'YOU EXPRESSLY WAIVE YOUR RIGHT TO PARTICIPATE IN ANY CLASS ACTION, COLLECTIVE ACTION, OR REPRESENTATIVE PROCEEDING AGAINST HELIX XI TECHNOLOGIES. ALL DISPUTES MUST BE BROUGHT IN YOUR INDIVIDUAL CAPACITY ONLY.' },
    ]
  },
  {
    number: '10',
    title: 'Miscellaneous',
    content: [
      { sub: '10.1', label: 'Entire Agreement.', text: 'These Terms constitute the entire agreement between you and Helix XI Technologies with respect to the subject matter hereof and supersede all prior and contemporaneous agreements, representations, warranties, and understandings.' },
      { sub: '10.2', label: 'Severability.', text: 'If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that the remaining provisions shall remain in full force and effect.' },
      { sub: '10.3', label: 'Waiver.', text: 'No waiver of any provision of these Terms shall be effective unless made in writing and signed by an authorized representative of Helix XI Technologies.' },
      { sub: '10.4', label: 'Amendment.', text: 'Helix XI Technologies reserves the right to modify these Terms at any time. Continued use of the Platform following notice of any modification constitutes acceptance of the modified Terms.' },
      { sub: '10.5', label: 'Force Majeure.', text: 'Helix XI Technologies shall not be liable for any failure or delay in performance resulting from circumstances beyond its reasonable control, including acts of God, natural disasters, government actions, cyberattacks, internet outages, or third-party service failures.' },
    ]
  },
  {
    number: '11',
    title: 'Contact Information',
    content: [
      { sub: '', text: 'For legal inquiries, notices, or questions regarding these Terms, please contact Helix XI Technologies through the official channels listed on the Platform. All formal legal notices must be submitted in writing.' },
    ]
  },
];

export default function Terms({ onClose }) {
  return (
    <div className="terms-overlay">
      <div className="terms-modal">

        <div className="terms-header">
          <div className="terms-header-left">
            <div className="terms-logo">
              <svg viewBox="0 0 160 160" xmlns="http://www.w3.org/2000/svg" width="28" height="28">
                <circle cx="80" cy="80" r="72" fill="none" stroke="#0891b2" strokeWidth="1.5" opacity="0.3"/>
                <path d="M80 24 L112 122 M80 24 L48 122 M57 88 L103 88" fill="none" stroke="#0891b2" strokeWidth="8" strokeLinecap="square"/>
                <circle cx="80" cy="18" r="5" fill="#0891b2"/>
              </svg>
            </div>
            <div>
              <div className="terms-company">HELIX XI TECHNOLOGIES</div>
              <div className="terms-product">ARIA Financial Intelligence Platform</div>
            </div>
          </div>
          <button className="terms-close" onClick={onClose}>✕</button>
        </div>

        <div className="terms-title-block">
          <h1 className="terms-title">Terms of Service & End User License Agreement</h1>
          <div className="terms-meta">
            <span className="terms-badge">Version 1.0.0</span>
            <span className="terms-badge">Effective Date: March 2026</span>
            <span className="terms-badge">Last Revised: March 2026</span>
          </div>
        </div>

        <div className="terms-body">
          <div className="terms-preamble">
            PLEASE READ THESE TERMS OF SERVICE CAREFULLY BEFORE ACCESSING, INSTALLING, CONFIGURING, OR OTHERWISE USING THE ARIA FINANCIAL INTELLIGENCE PLATFORM OPERATED BY HELIX XI TECHNOLOGIES. THIS AGREEMENT CONSTITUTES A LEGALLY BINDING CONTRACT BETWEEN YOU AND HELIX XI TECHNOLOGIES. BY ACCESSING OR USING THE PLATFORM IN ANY MANNER, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS IN THEIR ENTIRETY.
            <br /><br />
            IF YOU DO NOT AGREE TO THESE TERMS, YOU MUST IMMEDIATELY CEASE ALL USE OF THE PLATFORM AND UNINSTALL ALL ASSOCIATED SOFTWARE.
          </div>

          {SECTIONS.map(s => (
            <div key={s.number} className="terms-section">
              <div className="terms-section-header">
                <span className="terms-section-number">{s.number}</span>
                <h2 className="terms-section-title">{s.title}</h2>
              </div>
              {s.warning && <div className="terms-warning">{s.warning}</div>}
              {s.content.map((c, i) => (
                <div key={i} className="terms-clause">
                  {c.sub && <span className="terms-sub">{c.sub}</span>}
                  <p className="terms-text">
                    {c.label && <strong className="terms-label">{c.label} </strong>}
                    {c.text}
                  </p>
                </div>
              ))}
            </div>
          ))}

          <div className="terms-footer-block">
            <div className="terms-acceptance">
              BY USING THE PLATFORM, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.
            </div>
            <div className="terms-copyright">
              HELIX XI TECHNOLOGIES | ARIA FINANCIAL INTELLIGENCE PLATFORM<br />
              Version 1.0.0 | © 2026 Helix XI Technologies. All Rights Reserved.
            </div>
          </div>
        </div>

        <div className="terms-actions">
          <button className="terms-btn-accept" onClick={onClose}>I Agree — Close</button>
        </div>

      </div>
    </div>
  );
}
